//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IdPedido { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdMedicamento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Mediamento Mediamento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
